INFO:2017-03-20 23:12:20,782:loggen.py:Starting Task App Logger at 20170320_231220
INFO:2017-03-20 23:12:20,782:tasks_indiez.py:Starting tasks app
INFO:2017-03-20 23:12:20,784:_internal.py: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:2017-03-20 23:12:26,343:task_db.py:Task is = <pymongo.cursor.Cursor object at 0x7feb2dcd4f50>
ERROR:2017-03-20 23:12:26,343:task_db.py:404 - No task with 7 task_id
INFO:2017-03-20 23:12:26,344:_internal.py:127.0.0.1 - - [20/Mar/2017 23:12:26] "GET /task/get/7 HTTP/1.1" 200 -
INFO:2017-03-20 23:12:35,065:task_db.py:tasks list after 2017-03-20 = [{u'task_end_date': '2017-04-21', u'task_id': 6, u'task_create_date': '2017-03-19', u'task_description': u' 2nd update made to task', u'task_owner': u'bkallur', u'task_name': u'task_name_new'}, {u'task_end_date': '2017-04-08', u'task_id': 8, u'task_create_date': '2017-03-20', u'task_description': u'Ranjini Gunjini', u'task_owner': u'ranjini', u'task_name': u'R1_updated'}]
INFO:2017-03-20 23:12:35,066:_internal.py:127.0.0.1 - - [20/Mar/2017 23:12:35] "GET /task/list_after/2017-03-20 HTTP/1.1" 200 -
